version: "2"

networks:
  proxy-tier:
    external:
      name: caddy-proxy

services:
  caddy:
    container_name: caddy
    image: drlogout/caddy:0.9.5
    # remove -ca=https://acme-staging.api.letsencrypt.org/directory in production
    command: -conf /etc/caddy/config/Caddyfile -log stdout -agree -ca=https://acme-staging.api.letsencrypt.org/directory
    ports:
      - 80:80
      - 443:443
    volumes:
      - "../volumes/caddy/config:/etc/caddy/config"
      - "../volumes/caddy/certs:/etc/caddy/certs"
    environment:
      - CADDYPATH=/etc/caddy/certs
      - CADDYFILE=/etc/caddy/config/Caddyfile
    networks:
      - proxy-tier
    restart: always

  caddy-gen:
    container_name: caddy-gen
    image: jwilder/docker-gen:0.7.3
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "../volumes/docker-gen/templates:/etc/docker-gen/templates:ro"
      - "../volumes/docker-gen/config:/etc/docker-gen/config:ro"
    volumes_from:
      - caddy
    environment:
      LETSENCRYPT_EMAIL: "email@example.com"
    command: -config /etc/docker-gen/config/docker-gen.cfg
    restart: always
